"""gamma2.py -- Task C: gamma_2 = density of intersecting pairs of GOOD family-(1,3) lines,
per section 3 of docs/research/cubic_matching_local_law.md.

Method
------
Part (1) ground truth: from each dump's rec13 (every family-(1,3) line generated by
cube_matching_fast.py in the box, good or not -- "good" iff unc1=unc2=unc3=1), reconstruct the
three lattice points of every line, find all UNORDERED pairs of DISTINCT lines that share a
lattice point, and classify each pair by the roles (m,m') in {1,2,3}^2, m=index of the shared
point on line A, m'=index on line B (index order is arbitrary/unordered per pair -- see below).
Report counts of GOOD-GOOD pairs by unordered role-set {m,m'} (m<m'), and check m=m' never
occurs.

Part (2) model prediction: rather than re-deriving the abstract continuum (s,w') density
transfer law u -> u'=(a_m/a_m')u (which for the fractional ratios 1/4,1/5,-5/4,-4/5 requires an
extra "fine digit" u mod q, q in {4,5}, and is a genuinely delicate equidistribution argument --
see docs/research/cubic_matching_note.md sec.3, "estimated effort 1-2 days"), we evaluate the
model DIRECTLY on the actual, finite-p population of real lines already enumerated in rec13 (each
already satisfies the box constraints of its own line by construction -- exactly "the box
constraints of BOTH lines" required by the spec, since both member lines of every pair we look at
are real, individually box-admissible lines from the dump). For every pair of DISTINCT lines
sharing a lattice point (i.e. every REAL geometric incidence at this p -- good or not), we predict
   P(both good) = product of U(pos,thp,thm,delta,eps,x0/p) over the FIVE distinct residues
                  involved (shared residue counted once, its lift shared by both lines; the two
                  other residues of each line with their own lift), using U_model.U exactly as
                  specified in sec.3 ("the five residues have independent partner data").
This is the finite-p realization of the spec's continuum integral: summing the predicted
join-probability over the actual realized population of intersecting line pairs at this p is
what the continuum (s,w',rho,digit) integral is designed to approximate as p -> infinity for a
fixed box; it uses U_model.py exactly as instructed and needs no re-derivation of the u->u'
box-admissibility transfer law (which the *existing*, ground-truth-generated lines already
satisfy by construction).

Each physical pair, found once via the point-sharing dictionary, is scored once (predicted_single,
grouped into the 3 unordered role-set categories {1,2},{1,3},{2,3} -- directly comparable to the
ground truth of part 1). We ALSO report the spec's 6 "configurations" (1,2),(1,3),(2,1),(2,3),
(3,1),(3,2) explicitly: by construction/symmetry of the U-product (it does not depend on which
line is called "line 1"), config (m,m') and config (m',m) have EXACTLY the same value -- both
count the same physical role-set {m,m'} once, so config(m,m')=config(m',m)=predicted_single[{m,m'}]
and their sum (the literal Sum_configurations of spec's formula, which double-counts each pair
from both lines' perspective) equals 2*predicted_single_total.

usage: python3 gamma2.py
"""
import sys, os, itertools
from collections import defaultdict
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
from U_model import U

A1 = (-4, -1, 5)          # a_m, m=1,2,3 (1-indexed via A1[m-1])
CONFIGS = [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


def ratio_str(m, mp):
    num, den = A1[m - 1], A1[mp - 1]
    from fractions import Fraction
    r = Fraction(num, den)
    return str(r)


DUMPS = [
    ("p12809_box0_0", "/home/pmbot/projects/saturation_peer/slack/verification/cube_dump_p12809_box0_0.npz"),
    ("p12809_box-6404_0", "/home/pmbot/projects/saturation_peer/slack/verification/cube_dump_p12809_box-6404_0.npz"),
    ("p3203_box700_-2100", "/home/pmbot/projects/saturation_peer/slack/verification/cube_dump_p3203_box700_-2100.npz"),
]

log = []
def P(*a):
    s = " ".join(str(x) for x in a)
    print(s); log.append(s)


def analyze(name, path):
    d = np.load(path)
    p = int(d['p']); x0 = int(d['x0']); y0 = int(d['y0'])
    x0p = (x0 % p) / p
    pos = d['pos']; thp = d['thp']; thm = d['thm']
    rec13 = d['rec13']
    n_lines = len(rec13)
    P("=" * 100)
    P(f"dump {name}: p={p} x0={x0} y0={y0}  #family-(1,3) lines in box = {n_lines} ({n_lines/p:.4f} p)")

    # ---- build lines: points, residues, lifts, unc flags, good status ----
    us = rec13[:, 0]; vs = rec13[:, 1]; X1 = rec13[:, 2]; Y1 = rec13[:, 3]
    d1 = rec13[:, 4]; e1 = rec13[:, 5]; d2 = rec13[:, 6]; e2 = rec13[:, 7]
    d3 = rec13[:, 8]; e3 = rec13[:, 9]
    unc1 = rec13[:, 10]; unc2 = rec13[:, 11]; unc3 = rec13[:, 12]
    xr1 = rec13[:, 14]; xr2 = rec13[:, 15]; xr3 = rec13[:, 16]
    good = (unc1 == 1) & (unc2 == 1) & (unc3 == 1)

    P1x, P1y = X1, Y1
    P2x, P2y = X1 + us, Y1 + vs
    P3x, P3y = X1 + 3 * us, Y1 + 3 * vs

    # per-line, per-role U values and "other-two-product"
    # U_model.U takes scalar (python-int) d,e for a whole array, so group by the 4 lift combos.
    Uvals = np.empty((n_lines, 3), dtype=np.float64)
    for role, (xres, dd, ee) in enumerate([(xr1, d1, e1), (xr2, d2, e2), (xr3, d3, e3)]):
        out = np.empty(n_lines, dtype=np.float64)
        for dv, ev in itertools.product((0, 1), (0, 1)):
            m = (dd == dv) & (ee == ev)
            if m.any():
                out[m] = U(pos[xres[m]], thp[xres[m]], thm[xres[m]], dv, ev, x0p)
        Uvals[:, role] = out
    other2 = np.empty((n_lines, 3), dtype=np.float64)
    other2[:, 0] = Uvals[:, 1] * Uvals[:, 2]
    other2[:, 1] = Uvals[:, 0] * Uvals[:, 2]
    other2[:, 2] = Uvals[:, 0] * Uvals[:, 1]

    # ---- point dictionary: (X,Y) -> list of (line_idx, role[1..3]) ----
    point_dict = defaultdict(list)
    for role, (Px, Py) in enumerate([(P1x, P1y), (P2x, P2y), (P3x, P3y)], start=1):
        for i in range(n_lines):
            point_dict[(int(Px[i]), int(Py[i]))].append((i, role))

    # ---- enumerate all unordered pairs of DISTINCT lines sharing a point ----
    gt_roleset = defaultdict(int)      # ground truth: both lines good, key=(m,m') m<m'
    gt_total = 0
    gt_mm_equal = 0
    pred_roleset = defaultdict(float)  # model prediction (predicted_single), key=(m,m') m<m'
    pred_total = 0.0
    n_pairs_checked = 0
    seen_pairs = set()

    for pts, entries in point_dict.items():
        if len(entries) < 2:
            continue
        for (i, mi), (j, mj) in itertools.combinations(entries, 2):
            if i == j:
                continue
            key = (min(i, j), max(i, j))
            if key in seen_pairs:
                # same two lines sharing >1 point -- log but keep (shouldn't happen generically)
                pass
            seen_pairs.add(key)
            n_pairs_checked += 1
            if mi == mj:
                gt_mm_equal += 1
                continue
            rs = (min(mi, mj), max(mi, mj))
            if good[i] and good[j]:
                gt_roleset[rs] += 1
                gt_total += 1
            # shared residue check
            xi_shared = [xr1, xr2, xr3][mi - 1][i]
            xj_shared = [xr1, xr2, xr3][mj - 1][j]
            assert xi_shared == xj_shared, "shared point residue mismatch"
            sharedU = Uvals[i, mi - 1]
            sharedU_j = Uvals[j, mj - 1]
            assert abs(sharedU - sharedU_j) < 1e-12, "shared U mismatch between the two lines"
            predval = sharedU * other2[i, mi - 1] * other2[j, mj - 1]
            pred_roleset[rs] += predval
            pred_total += predval

    P(f"  #distinct point-sharing line pairs checked = {n_pairs_checked} ({n_pairs_checked/p:.4f} p);  m=m' occurrences = {gt_mm_equal} (should be 0)")
    P(f"  --- part (1) ground truth: GOOD-GOOD pairs by unordered role-set {{m,m'}} ---")
    for rs in [(1, 2), (1, 3), (2, 3)]:
        c = gt_roleset.get(rs, 0)
        P(f"    {{{rs[0]},{rs[1]}}}: {c:5d}  ({c/p:.4f} p)")
    P(f"    TOTAL good-good pairs: {gt_total} ({gt_total/p:.4f} p)")

    P(f"  --- part (2) model prediction: sum of P(both good)=prod(5 U's) over ALL real intersecting pairs, by role-set ---")
    for rs in [(1, 2), (1, 3), (2, 3)]:
        v = pred_roleset.get(rs, 0.0)
        gtc = gt_roleset.get(rs, 0)
        P(f"    {{{rs[0]},{rs[1]}}}: predicted={v:.3f} ({v/p:.4f} p)   empirical(good-good)={gtc} ({gtc/p:.4f} p)   diff/p={ (v-gtc)/p:+.4f}")
    P(f"    TOTAL predicted gamma2*p = {pred_total:.3f} ({pred_total/p:.4f} p)   empirical total = {gt_total} ({gt_total/p:.4f} p)   diff/p={(pred_total-gt_total)/p:+.4f}")

    P(f"  --- spec's 6 configurations (m,m') [config(m,m')=config(m',m)=predicted_single{{m,m'}} by U-product symmetry] ---")
    for (m, mp) in CONFIGS:
        rs = (min(m, mp), max(m, mp))
        v = pred_roleset.get(rs, 0.0)
        P(f"    config ({m},{mp})  [a_{m}/a_{mp}={ratio_str(m,mp)}]:  predicted = {v:.3f} ({v/p:.4f} p)")
    sum6 = 2 * pred_total
    P(f"    Sum over the 6 listed configurations (spec's literal gamma2 sum, double-counts each pair from both lines' perspective) = {sum6:.3f} ({sum6/p:.4f} p) = 2 x total_predicted")

    return dict(p=p, gt_total=gt_total, pred_total=pred_total, gt_roleset=dict(gt_roleset), pred_roleset=dict(pred_roleset))


if __name__ == "__main__":
    results = {}
    for name, path in DUMPS:
        results[name] = analyze(name, path)

    P("=" * 100)
    P("SUMMARY (total gamma2*p, i.e. the count comparable to |M| >= #good - #pairs):")
    for name, r in results.items():
        p = r['p']
        P(f"  {name}: p={p}  empirical pairs/p = {r['gt_total']/p:.4f}   model gamma2 = {r['pred_total']/p:.4f}   diff/p = {(r['pred_total']-r['gt_total'])/p:+.4f}")

    log_path = "/home/pmbot/projects/saturation_peer/slack/verification/g39_gamma2.txt"
    with open(log_path, "w") as fh:
        fh.write("\n".join(log) + "\n")
    print(f"\nlog written to {log_path}")
